if [[ $JITPACK_VERSION == v* ]]
then
  echo "BUILD VERSION: ${JITPACK_VERSION:1}"
  env PLUGIN_VERSION=${JITPACK_VERSION:1} mvn package
else
  echo "BUILD VERSION: ${JITPACK_VERSION}-SNAPSHOT"
  env PLUGIN_VERSION=${JITPACK_VERSION}-SNAPSHOT mvn package
fi