name: ${project.artifactId}
description: ${plugin-description}
author: ${plugin-author}
main: me.dpohvar.powernbt.PowerNBT
website: ${plugin-website}
version: ${project.version}
commands:
    powernbt:
        description: use nbt commands
        usage: /nbt ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt
            - nbt
    powernbt.:
        description: use nbt commands (silent mode)
        usage: /nbt. ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt.
            - nbt.

